name: "GO CI"

on:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.3']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build
      - name: Get file list
        run: ls -A
      - name: Run quick sort test
        run: go test -v ./...
      - name: run code linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
